FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 24577
WORKDIR /
COPY xs-encryption-application.jar /xs-encryption-application.jar
ENTRYPOINT ["java","-jar","xs-encryption-application.jar"]