FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 20564
WORKDIR /
COPY xs-article-search-application.jar /xs-article-search-application.jar
ENTRYPOINT ["java","-jar","xs-article-search-application.jar"]