FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 26577
WORKDIR /
COPY xs-address-application.jar /xs-address-application.jar
ENTRYPOINT ["java","-jar","xs-address-application.jar"]