server:
  port: 12577
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka  server交互的地址和注册服务都需要依赖这个地址
spring:
  application:
    name: xseurekaserver
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt