FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 20577
WORKDIR /
COPY xs-service-gateway-application.jar /xs-service-gateway-application.jar
ENTRYPOINT ["java","-jar","xs-service-gateway-application.jar"]