FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 16577
WORKDIR /
COPY xs-article-liked-application.jar /xs-article-liked-application.jar
ENTRYPOINT ["java","-jar","xs-article-liked-application.jar"]