server:
  port: 22577
spring:
  application:
    name: xs-config-center
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XiaoShuaiRKK/XS-Assistant-Config-Repo.git
          search-paths:
            - XS-Assistant-Config-Repo
          force-pull: true
          default-label: main
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka