FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 15577
WORKDIR /
COPY xs-article-application.jar /xs-article-application.jar
ENTRYPOINT ["java","-jar","xs-article-application.jar"]