server:
  port: 30577
  servlet:
    context-path: /xs_assistant/chat
spring:
  application:
    name: xs-chat
  data:
    redis:
      host: 127.0.0.1
      port: 5050
      jedis:
        pool:
          enabled: true
          max-active: -1
          max-wait: 8s
          max-idle: 100
          min-idle: 0
      timeout: 2400
      password: xs0628
eureka:
  client:
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka
  instance:
    prefer-ip-address: true