FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 11577
WORKDIR /
COPY xs-account-application.jar /xs-account-application.jar
ENTRYPOINT ["java","-jar","xs-account-application.jar"]