server:
  port: 20577
spring:
  application:
    name: xs-service-gateway
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
  data:
    redis:
      host: 127.0.0.1
      port: 5050
      jedis:
        pool:
          enabled: true
          max-active: -1
          max-wait: 8s
          max-idle: 100
          min-idle: 0
      timeout: 2400
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: xs-service-login-gateway
          uri: lb://XS-LOGIN
          predicates:
            - Path=/xs_assistant/login/**
        - id: xs-service-user
          uri: lb://XS-SERVICE-USER
          predicates:
            - Path=/xs_assistant/user/**
        - id: xs-account
          uri: lb://XS-ACCOUNT
          predicates:
            - Path=/xs_assistant/account/**
        - id: xs-article-gateway
          uri: lb://XS-ARTICLE
          predicates:
            - Path=/xs_assistant/article/**
        - id: xs-article-liked-gateway
          uri: lb://XS-ARTICLE
          predicates:
            - Path=/xs_assistant/liked/**
eureka:
  instance:
    hostname: xs-service-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka