server:
  port: 11577
  servlet:
    context-path: /xs_assistant
spring:
  application:
    name: xs-account
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 5050
      jedis:
        pool:
          enabled: true
          max-active: -1
          max-wait: 8s
          max-idle: 100
          min-idle: 0
      timeout: 2400
      password: xs0628
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka
  instance:
    prefer-ip-address: true

resilience4j.retry:
  instances:
    login-api:
      max-attempts: 3
      wait-duration: 1s
############### Micrometer Tracing + Zipkin 链路追踪 ###############
management:
  tracing:
    sampling:
      probability: 1.0 #设置跟踪采样的概率为100%(1.0),这意味着应用程序处理的所有请求都被跟踪,如果是10%(0.1)则为10条请求只有1条跟踪
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-} #日志记录格式
springdoc:
  swagger-ui:
    path: /swagger