server:
  port: 14577
  servlet:
    context-path: /xs_assistant
spring:
  application:
    name: xs-code
  data:
    redis:
      port: 5050
      host: 127.0.0.1
      password: xs0628
  rabbitmq:
    host: 127.0.0.1
    username: xs
    password: xs0628
    virtual-host: /xs-assistant-virtual
    port: 5672
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka
