FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 12577
WORKDIR /
COPY xs-cloud-eureka-application.jar /xs-cloud-eureka-application.jar
ENTRYPOINT ["java","-jar","xs-cloud-eureka-application.jar"]