minio:
  bucket: xs-assistant-bucket
  endpoint: http://10.10.100.120:9090
  access-key: minioadmin
  secret-key: minioadmin
eureka:
  client:
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka
  instance:
    prefer-ip-address: true