FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 22577
WORKDIR /
COPY xs-config-center-application.jar /xs-config-center-application.jar
ENTRYPOINT ["java","-jar","xs-config-center-application.jar"]