server:
  port: 20564
  servlet:
    context-path: /xs_assistant/search
spring:
  application:
    name: xs-article-search
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
  elasticsearch:
    uris: http://127.0.0.1:9200
  rabbitmq:
    host: 127.0.0.1
    username: xs
    password: xs0628
    virtual-host: /xs-assistant-virtual
    port: 5672
    listener:
      type: simple
      simple:
        acknowledge-mode: auto
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:12577/eureka
  instance:
    prefer-ip-address: true
############### Micrometer Tracing + Zipkin 链路追踪 ###############
management:
  tracing:
    sampling:
      probability: 1.0 #设置跟踪采样的概率为100%(1.0),这意味着应用程序处理的所有请求都被跟踪,如果是10%(0.1)则为10条请求只有1条跟踪
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-} #日志记录格式
  level:
    org.springframework.data.mongodb.core: debug