server:
  port: 16577
  servlet:
    context-path: /xs_assistant
spring:
  application:
    name: xs-article-liked
  banner:
    charset: UTF-8
    location: Banner/XS-Assistant-Banner.txt
  datasource:
    username: root
    password: xiaoshuai0628
    url: jdbc:mysql://10.10.100.105:3306/xs?useUnicode=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      jedis:
        pool:
          enabled: true
          max-active: -1
          max-wait: 8s
          max-idle: 100
          min-idle: 0
      timeout: 2400
      password: xs0628
      host: 10.10.100.105
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
resilience4j:
  circuitbreaker:
    instances:
      liked-api:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: TIME_BASED
        failure-rate-threshold: 20
        wait-duration-in-open-state: 3s
        event-consumer-buffer-size: 10
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.100.88:12577/eureka
  instance:
    prefer-ip-address: true
management:
  zipkin:
    tracing:
      endpoint: http://10.10.100.105:9411/api/v2/spans