FROM openjdk:17-jdk-alpine
MAINTAINER XiaoShuaiRKK@github.com
EXPOSE 15628
WORKDIR /
COPY xs-article-hot-application.jar /xs-article-hot-application.jar
ENTRYPOINT ["java","-jar","xs-article-hot-application.jar"]